log_file: "./log/development.log"
pid_file: "./pids/service.pid"

db_string: "user=massliking password=massliking host=localhost port=5432 dbname=massliking sslmode=disable"

app_address: "localhost:8081"

jwt:
  realm: "Develop"
  secret: "aigh7eiw8ohc6sheinood1mi3aeshudaigh7mueP0OoSieyohy"
  ttl: 12

limits:
  trusted:
    likes:     1000
    comments:  200
    follows:   1000
    unfollows: 1000
  non_trusted:
    likes:     500
    comments:  100
    follows:   500
    unfollows: 500
