---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=yes
  with_items:
    - postgresql-{{ pg_version }}
    - python3-psycopg2
    - postgresql-contrib-{{pg_version}}
    - libpq-dev

- name: Check service
  service: name=postgresql state=started enabled=yes

- name: Create database
  become_user: postgres
  become: yes
  postgresql_db: name={{ db_name }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Setup database access
  become_user: postgres
  become: yes
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
                   encrypted=no



- name: Check access
  become_user: postgres
  become: yes
  postgresql_user: name={{ db_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present
